frontend/config/routes.rb
Frontend::Application.routes.draw do

  resources :users  do
    resources :hosts
  end

  root :to => "entities#index"

  resources :entities

  resource :sessions do
    member do
      get 'new'
      delete 'destroy'
      post 'create'
    end
  end

  match "users/:user_id/hosts/:id/tokens/new"  => "hosts#new_auth_token"   , :as => :new_auth_token  , :via => :get
  match "users/:user_id/hosts/:id/tokens/"  => "hosts#create_auth_token"   , :as => :create_auth_token , :via => :post

  match "users/:id/enable-host" => "users#enable_host" , :as => :enable_host, :via => :put

  match "logout" => "sessions#destroy"

end

frontend/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
  <title>
    lichtflut Forschungs- und Entwicklungsgesellschaft mbH
  </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "init.css", "site-structure.css", "content.css", "slideshow.css", :media => "screen" %>
  <%= javascript_include_tag "application" , "jquery-1.7.1.min.js" , "lichtflut-web.js" %>

  <%= csrf_meta_tags %>

  <meta content="text/html;charset=utf-8">
  <meta charset="utf-8">

  <!--[if IE 6]>
  <style type="text/css">@import url(css/ie6.css);</style>
  <![endif]-->


</head>
<body>
<div id="page-background">
  <img src="<%= asset_path('site_background.png') %>" width="100%" height="100%" alt="background">
</div>
<div id="site-wrapper">
  <div id="site-header">
    <div id="header-top-line">
      <span class="delim-small">&gt;</span>
      <% if session[:current_user].nil? %>
          <%= link_to 'Login', :controller => :sessions, :action => :new %>
      <% else %>
          <%= link_to 'Logout', logout_path %>
      <% end %>
      <!--<span class="delim-small">&gt;</span>
      <a href="stellenangebote.html">Jobs</a>
      <span class="delim-small">&gt;</span>
      <a href="kontakt.html">Kontakt</a>       -->
    </div>
    <div id="header-middle-line">
      <span class="logo">lichtflut</span> <span class="logo-extension"><em style="font-size: 20pt;">EntityBrowser</em> </span>
    </div>
    <div id="header-navigation">
      <% if session[:current_user] %>
          <div class="menu-item <%= controller_name.include?("entities") ?  "active" : "" %>">
            <%= link_to 'Entities', entities_path %>
          </div>
          <div class="menu-item <%= controller_name.include?("users") ?  "active" : "" %>">
            <%= link_to 'Profile', user_path(session[:current_user]) %>
          </div>
          <div class="menu-item <%= controller_name.include?("host") ?  "active" : "" %>">
            <%= link_to 'Host monitor', user_hosts_path(session[:current_user].id) %>
          </div>
      <% end %>
      <div class="menu-item-delim"></div>
      <!--<div class="menu-item">
        <a href="unternehmen.html">Test</a>
      </div>    -->
    </div>
  </div>
  <div id="site-main">
    <br />
    <p></p>
    <% if flash[:alert] %>
        <p class="flash-error"><%= flash[:alert] %></p>
    <% end %>
    <% if flash[:notice] %>
        <p class="flash-notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>

  </div>
</div>
</body>
</html>