frontend/config/routes.rb
Frontend::Application.routes.draw do

  resources :users  do
    resources :hosts
  end

  root :to => "entities#index"

  resources :entities

  resource :sessions do
    member do
      get 'new'
      delete 'destroy'
      post 'create'
    end
  end

  match "users/:user_id/hosts/:id/tokens/new"  => "hosts#new_auth_token"   , :as => :new_auth_token  , :via => :get
  match "users/:user_id/hosts/:id/tokens/"  => "hosts#create_auth_token"   , :as => :create_auth_token , :via => :post

  match "users/:id/enable-host" => "users#enable_host" , :as => :enable_host, :via => :put

  match "logout" => "sessions#destroy"

end

frontend/app/models/host.rb
require 'rest_client'

class Host < ActiveRecord::Base
  attr_accessible :auth_token, :service_uri, :alias
  belongs_to :user

  def is_alive?
    response = nil
    begin
      response = RestClient.get self.service_uri do |r, request, result|
        r
      end
    rescue Exception
    end

    if(response.nil? || !response.code.eql?(200))
      return false
    else
      if response.to_s.include?"http://rb.lichtflut.de/rels/self"
        return true
      else
        return false
      end
    end
  end
  validates :service_uri, :presence  => true

end

frontend/app/controllers/hosts_controller.rb
class HostsController < ApplicationController

  before_filter :check_authorization

  # GET user/user_id/hosts
  def index
    user_id = params[:user_id]
    @hosts = Host.find_all_by_user_id user_id
  end

# GET user/user_id/hosts/1

  def show
    @host = Host.find_by_user_id_and_id(session[:current_user], params[:id])
    render :action => :edit
  end

# GET /hosts/new
# GET /hosts/new.json
  def new
    @host = Host.new
  end

# GET user/user_id/hosts/1/edit
  def edit
    @host = Host.find_by_user_id_and_id(session[:current_user], params[:id])
  end

# POST user/user_id/hosts
  def create
    @host = Host.new(params[:host])
    @host.user_id=params[:user_id]

    respond_to do |format|
      if @host.save
        flash[:notice] = "Host was successfully created."
        redirect_to user_hosts_path(session[:current_user]) and return
      else
        format.html { render action: "new" }
      end
    end
  end

# PUT user/user_id/hosts/1
  def update
    @host = Host.find_by_user_id_and_id(params[:user_id], params[:id])

    respond_to do |format|
      if @host.update_attributes(params[:host])
        format.html { redirect_to [session[:current_user],@host], notice: 'Host was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def new_auth_token
    @host = Host.find_by_user_id_and_id(params[:user_id], params[:id])
  end

  def create_auth_token
    @host = Host.find_by_user_id_and_id(params[:user_id], params[:id])

    RestClient.log = Logger.new(STDOUT)

    login = params[:userID]
    passwd = params[:passwd]

    response = RestClient.post @host.service_uri + "/auth", {'password' => passwd, 'id' => login}.to_json, :content_type => :json do |response, request, result|
      response
    end

    if(response.code.eql?(201))
      token = response.cookies["lfrb-session-auth"]
      token = CGI::unescape(token)
      unless token.nil?
        @host.auth_token= token
        @host.save!
        redirect_to user_hosts_path(session[:current_user], @host) and return
      end
    end
    flash[:alert] = "Authentication went wrong, please try it again!"
    render :action => :new_auth_token
  end



# DELETE user/user_id/hosts/1
  def destroy
    @host = Host.find_by_user_id_and_id(params[:user_id], params[:id])
    @host.destroy
    respond_to do |format|
      format.html { redirect_to user_hosts_url }
    end
  end
end

frontend/app/helpers/hosts_helper.rb
module HostsHelper
end

frontend/app/views/hosts/_form.html.erb
<%= form_for [session[:current_user], @host] do |f| %>
  <% if @host.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@host.errors.count, "error") %> prohibited this host from being saved:</h2>

      <ul>
      <% @host.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :service_uri %><br />
    <%= f.text_field :service_uri %>
  </div>

    <div class="field">
      <%= f.label :alias %><br />
      <%= f.text_field :alias %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

frontend/app/views/hosts/edit.html.erb
<h1>Editing host</h1>

<%= render 'form' %>

<%= link_to 'Back', user_hosts_path(session[:current_user]) %>

frontend/app/views/hosts/index.html.erb
<h1>Configured hosts</h1>

<table class="login-table" border="1">
  <tr>
    <th style="padding: 4px; vertical-align: top;">Service location</th>
    <th style="padding: 4px; vertical-align: top;">Alias</th>
    <th style="padding: 4px; vertical-align: top;">Authtoken</th>
    <th style="padding: 4px; vertical-align: top;">Is alive?</th>
    <th style="padding: 4px; vertical-align: top;"></th>
    <th style="padding: 4px; vertical-align: top;"></th>
    <th style="padding: 4px; vertical-align: top;"></th>
  </tr>

  <% @hosts.each do |host| %>
      <% enabled = !session[:current_user].active_host.nil?() && session[:current_user].active_host.id.eql?(host.id)  %>
      <% color = enabled ? "DAF5CF" : "FFFFFF" %>
      <tr>
        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= host.service_uri %></td>
        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= host.alias %></td>
        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= host.auth_token %></td>
        <% if host.is_alive?  %>
            <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><b><font color="00FF00">true</font></b></td>
        <% else %>
            <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><b><font color="FF0000">false</font></b></td>
        <% end %>

        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= link_to 'Edit', edit_user_host_path(session[:current_user],host) %></td>
        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= link_to 'Destroy', [session[:current_user],host], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;"><%= link_to 'Add token', new_auth_token_path(session[:current_user], host), data: { confirm: 'Are you sure?' }  %></td>
        <% if !session[:current_user].active_host.nil?() && session[:current_user].active_host.id.eql?(host.id) %>
            <td bgcolor="<%=color %>" style="padding: 4px; vertical-align: top;">Enabled</td>
        <% else %>
            <td  bgcolor="<%=color %>"style="padding: 4px; vertical-align: top;">
              <%= form_tag enable_host_path(session[:current_user]), :html => { :class => "button_to" }, :method => :put do %>
                  <%= hidden_field_tag :host, host.id %>
                  <button type="submit"><span>Enable</span></button>
              <% end %>
            </td>
        <% end %>

      </tr>
  <% end %>
</table>

<br />

<%= link_to 'Add new host', new_user_host_path(session[:current_user]) %>

frontend/app/views/hosts/new.html.erb
<h1>New host</h1>

<%= render 'form' %>

<%= link_to 'Back', user_hosts_path(session[:current_user]) %>

frontend/app/views/hosts/new_auth_token.html.erb
<h1>Creating Authtoken for <%= @host.alias %></h1>
<br />
<p></p>

<fieldset>
<%= form_tag create_auth_token_path(session[:current_user],@host) do %>
    <table class="login-table">
      <tr>
        <td style="padding: 4px; vertical-align: top;" width="180"><label for="login">UserID</label></td>
        <td style="padding: 4px; vertical-align: top;"><%= text_field_tag :userID %></td>
      </tr>
      <tr>
        <td style="padding: 4px; vertical-align:top;" width="180"> <label for="login">Password</label></td>
        <td style="padding: 4px; vertical-align:top;" > <%= password_field_tag :passwd %></td>
      </tr>
      <tr>
        <td style="padding: 4px; vertical-align: top;" colspan="2">
          <button type="submit"><span>Create</span></button>
        </td>
      </tr>
    </table>
<%end %>
</fieldset>